name: Deploy Frontend to Develop

on:
  push:
    branches:
      - "develop"
    
jobs:
  deploy_frontend:
    name: Deploy Frontend to Develop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH Into Server and Build Frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 165.22.218.55
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "🚀 Starting Frontend Deployment..."
            cd /
            cd /products/restorent_pos_management/frontend/restaurant-pos-fe/

            echo "📥 Pulling latest changes..."
            git pull origin develop
            git log -1

            echo "📦 Installing dependencies..."
            npm install
            echo "🔨 Building frontend..."
            npm run build


            echo "🧹 Preparing build folders..."
            mkdir -p old_builds

            if [ -d "old_builds/build" ]; then
              echo "🗑️ Removing previous backup build..."
              rm -rf old_builds/build
            fi

            if [ -d "build" ]; then
              echo "📦 Backing up current build..."
              mv build old_builds/
            fi

            
            echo "✅ Frontend deployment completed."
